//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBooks
    {
        public int BorrowedBookID { get; set; }
        public string Identification { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual books books { get; set; }
        public virtual students students { get; set; }
    }
}
